apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: explorewithnk-keycloak-cert
  namespace: cert-manager
spec:
  secretName: explorewithnk-keycloak-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: keycloak.explorewithnk.com
  dnsNames:
  - keycloak.explorewithnk.com

# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: keycloak-ingress
#   namespace: keycloak
#   annotations:
#     kubernetes.io/ingress.class: "nginx"
#     cert-manager.io/cluster-issuer: "letsencrypt-prod"
#     nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
#     nginx.ingress.kubernetes.io/ssl-redirect: "true"
# spec:
#   tls:
#   - hosts:
#     - keycloak.explorewithnk.com
#     secretName: explorewithnk-keycloak-tls
#   rules:
#   - host: keycloak.explorewithnk.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: keycloak-app
#             port:
#               number: 80 # Changed to http instead of https
