apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: explorewithnk-keycloak-cert
  namespace: cert-manager
spec:
  secretName: explorewithnk-keycloak-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: keycloak.explorewithnk.com
  dnsNames:
  - keycloak.explorewithnk.com
