apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: explorewithnk-vault-cert
  namespace: cert-manager
spec:
  secretName: vaultwarden-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: vault.explorewithnk.com
  dnsNames:
    - vault.explorewithnk.com
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-backend
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/ignore-health: "true"
spec:
  provider:
    webhook:
      url: "http://vaultwarden.default.svc.cluster.local/api"
      result:
        jsonPath: "$.data"
