server.port=8080
spring.application.name=spring-app

# PostgreSQL Datasource
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgresql.default.svc.cluster.local:5432/app_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgrespassword123}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Valkey / Redis Configuration
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:valkey.default.svc.cluster.local}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.timeout=2000

# Apache Kafka Configuration
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka.default.svc.cluster.local:9092}
spring.kafka.consumer.group-id=spring-app-consumer-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Keycloak OpenID Connect (OAuth2 Resource Server)
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_AUTH_SERVER_URL:http://keycloak-app.keycloak.svc.cluster.local:8080/realms/master}

# Actuator & Prometheus Metrics
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.endpoint.prometheus.access=unrestricted
management.prometheus.metrics.export.enabled=true

# Logging
logging.level.root=INFO
logging.level.com.explorewithnk.springapp=INFO
