apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: public-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
  - port: 80
    name: http
    protocol: HTTP
    hosts:
    - "*." # matches all subdomains
    - "explorewithnk.com"
    tls:
      httpsRedirect: true
  - port: 443
    name: https
    protocol: HTTPS
    hosts:
    - "*."
    - "explorewithnk.com"
    tls:
      mode: SIMPLE
      credentialName: explorewithnk-com-tls
