apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: public-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP # ✅ Correct location
    hosts:
    - "*.explorewithnk.com"
    - "explorewithnk.com"
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS # ✅ Correct location
    hosts:
    - "*.explorewithnk.com"
    - "explorewithnk.com"
    tls:
      mode: SIMPLE
      credentialName: explorewithnk-com-tls
