apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: public-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
    hosts:
    - "*.explorewithnk.com"
    - "explorewithnk.com"
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
    hosts:
    - "*.explorewithnk.com"
    - "explorewithnk.com"
    tls:
      mode: SIMPLE
      credentialName: explorewithnk-com-tls
