# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: istio-ingressgateway
#     app.kubernetes.io/instance: istio
#     app.kubernetes.io/managed-by: Helm
#     app.kubernetes.io/name: istio-ingressgateway
#     app.kubernetes.io/part-of: istio
#     app.kubernetes.io/version: 1.26.3
#     helm.sh/chart: istio-ingress-1.26.3
#     install.operator.istio.io/owning-resource: unknown
#     install.operator.istio.io/owning-resource-namespace: istio-system
#     istio: ingressgateway
#     istio.io/rev: default
#     operator.istio.io/component: IngressGateways
#     operator.istio.io/managed: Reconcile
#     operator.istio.io/version: 1.26.3
#     release: istio
#   name: istio-ingressgateway
#   namespace: istio-system
# spec:
#   externalIPs:
#   - 180.188.231.97 # Replace with your VPS's static public IP
#   ports:
#   - name: status-port
#     port: 15021
#     protocol: TCP
#     targetPort: 15021
#   - name: http2
#     port: 80
#     protocol: TCP
#     targetPort: 8080
#   - name: https
#     port: 443
#     protocol: TCP
#     targetPort: 8443
#   - name: tcp
#     port: 31400
#     protocol: TCP
#     targetPort: 31400
#   - name: tls
#     port: 15443
#     protocol: TCP
#     targetPort: 15443
#   selector:
#     app: istio-ingressgateway
#     istio: ingressgateway
#   type: NodePort
