# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: explorewithnk-com-cert
#   namespace: istio-system # Same namespace as the ingress gateway
# spec:
#   secretName: explorewithnk-com-tls # Must match credentialName in Gateway
#   issuerRef:
#     name: letsencrypt-prod
#     kind: ClusterIssuer
#   dnsNames:
#   - explorewithnk.com
#   - "*.explorewithnk.com" # Optional wildcard
# wildcard-certificate.yaml


# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: explorewithnk-cert
#   namespace: cert-manager
# spec:
#   secretName: explorewithnk-tls
#   issuerRef:
#     name: letsencrypt-prod
#     kind: ClusterIssuer
#   commonName: explorewithnk.com
#   dnsNames:
#   - explorewithnk.com
#   - "*.explorewithnk.com"
#   secretTemplate:
#     annotations:
#       replicator.v1.mittwald.de/replicate-to: "*"

## using certificate per respective host please refer homepage deployment