# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: homepage
#   namespace: default
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: homepage
#   template:
#     metadata:
#       labels:
#         app: homepage
#     spec:
#       containers:
#       - name: homepage
#         image: nginx
#         ports:
#         - containerPort: 80
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: homepage
#   namespace: default
# spec:
#   selector:
#     app: homepage
#   ports:
#   - port: 80
#     targetPort: 80
# ---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
      - image: docker.io/nikhil12894/vps-landing:v1.0.1
        name: homepage
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: default
spec:
  selector:
    app: homepage
  ports:
  - port: 80
    targetPort: 80
