apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: explorewithnk-argocd-cert
  namespace: cert-manager
spec:
  secretName: explorewithnk-argocd-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: argocd.explorewithnk.com
  dnsNames:
  - argocd.explorewithnk.com
---


# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: argocd
#   namespace: argocd
#   annotations:
#     kubernetes.io/ingress.class: "nginx"
#     cert-manager.io/cluster-issuer: "letsencrypt-prod"
#     nginx.ingress.kubernetes.io/ssl-redirect: "true"
# spec:
#   tls:
#   - hosts:
#     - argocd.explorewithnk.com
#     secretName: explorewithnk-argocd-tls
#   rules:
#   - host: argocd.explorewithnk.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: argocd-server
#             port:
#               number: 80

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: argocd-ingress
#   namespace: argocd
#   annotations:
#     kubernetes.io/ingress.class: "nginx"
#     cert-manager.io/cluster-issuer: "letsencrypt-prod"
#     nginx.ingress.kubernetes.io/ssl-redirect: "true"
#     # nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
# spec:
#   tls:
#   - hosts:
#     - argocd.explorewithnk.com
#     secretName: explorewithnk-argocd-tls
#   rules:
#   - host: argocd.explorewithnk.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: argocd-server
#             port:
#               name: https

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: argocd-ingress
#   namespace: argocd
#   annotations:
#     kubernetes.io/ingress.class: "nginx"
#     cert-manager.io/cluster-issuer: "letsencrypt-prod"
#     nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
#     nginx.ingress.kubernetes.io/ssl-redirect: "true"
# spec:
#   tls:
#   - hosts:
#     - argocd.explorewithnk.com
#     secretName: explorewithnk-argocd-tls
#   rules:
#   - host: argocd.explorewithnk.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: argocd-server
#             port:
#               name: http # Changed to http instead of https
