# Enable and configure each component
grafana:
  enabled: true
  adminPassword: "fsddsggsfs"
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
    - grafana.explorewithnk.com
    tls:
    - hosts:
      - grafana.explorewithnk.com
      secretName: explorewithnk-grafana-tls # cert-manager will create this secret for you

prometheus:
  enabled: true
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false # Important for Istio integration
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    podMonitorSelector: {}
    probeSelector: {}
    ruleSelector: {}

alertmanager:

  ## Deploy alertmanager
  ##
  enabled: false
