apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-a
  template:
    metadata:
      labels:
        app: app-a
    spec:
      containers:
      - name: app-a-container
        image: nginxdemos/hello:plain-text
        ports:
        - containerPort: 80
        env:
        - name: MESSAGE
          value: "Hello from App A!"
---
apiVersion: v1
kind: Service
metadata:
  name: app-a-service
spec:
  selector:
    app: app-a
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
