global:
  domain: argocd.explorewithnk.com

configs:
  params:
    server.insecure: true

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    hosts:
    - argocd.explorewithnk.com
    tls:
    - hosts:
      - argocd.explorewithnk.com
      secretName: explorewithnk-argocd-tls # or whatever you like
