apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: 'https://github.com/Nikhil12894/k3s-gitops.git'
    targetRevision: HEAD
    path: manifests/keycloak
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
